#!/usr/bin/env node
// @generated by mcporter@0.9.0 on 2026-06-24T16:24:27.353Z. DO NOT EDIT.
import { Command } from 'commander';
import { createRuntime, createServerProxy } from 'mcporter';
import { createCallResult } from 'mcporter';

const embeddedServer = {
  "name": "linkedin",
  "description": "LinkedInMCP",
  "command": {
    "kind": "stdio",
    "command": "/home/maeste/.hermes/node/bin/linkedin-mcp",
    "args": [],
    "cwd": "/home/maeste/knowledge-bases/agent-me-kb/config"
  },
  "auth": "oauth",
  "source": {
    "kind": "local",
    "path": "/home/maeste/knowledge-bases/agent-me-kb/config/mcporter.json"
  },
  "sources": [
    {
      "kind": "local",
      "path": "/home/maeste/knowledge-bases/agent-me-kb/config/mcporter.json"
    }
  ]
} as const;
const embeddedSchemas = {
  "linkedin_login": {
    "type": "object"
  },
  "linkedin_callback": {
    "type": "object",
    "properties": {
      "code": {
        "type": "string",
        "description": "Code d'autorisation reçu de LinkedIn"
      },
      "state": {
        "type": "string",
        "description": "État de la requête pour vérification"
      }
    },
    "required": [
      "code",
      "state"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "linkedin_check_auth": {
    "type": "object",
    "properties": {},
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "linkedin_logout": {
    "type": "object",
    "properties": {},
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "linkedin_create_post": {
    "type": "object",
    "properties": {
      "text": {
        "type": "string",
        "description": "Contenu textuel de la publication"
      },
      "visibility": {
        "type": "string",
        "enum": [
          "PUBLIC",
          "CONNECTIONS"
        ],
        "default": "PUBLIC",
        "description": "Visibilité de la publication"
      },
      "mediaUrls": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "URLs des médias à joindre à la publication"
      }
    },
    "required": [
      "text"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "linkedin_get_person_urn": {
    "type": "object",
    "properties": {},
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "linkedin_diagnostic_user_info": {
    "type": "object",
    "properties": {},
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  }
} as const;
const embeddedName = "linkedin";
const embeddedDescription = "LinkedInMCP";
const generatorInfo = "Generated by mcporter@0.9.0 — https://github.com/steipete/mcporter";
const generatorTools = [
  {
    "name": "linkedin-login",
    "description": "",
    "usage": "linkedin-login [--raw <json>]",
    "flags": "[--raw <json>]"
  },
  {
    "name": "linkedin-callback",
    "description": "",
    "usage": "linkedin-callback --code <code> --state <state> [--raw <json>]",
    "flags": "--code <code> --state <state> [--raw <json>]"
  },
  {
    "name": "linkedin-check-auth",
    "description": "",
    "usage": "linkedin-check-auth [--raw <json>]",
    "flags": "[--raw <json>]"
  },
  {
    "name": "linkedin-logout",
    "description": "",
    "usage": "linkedin-logout [--raw <json>]",
    "flags": "[--raw <json>]"
  },
  {
    "name": "linkedin-create-post",
    "description": "",
    "usage": "linkedin-create-post --text <text> [--visibility <visibility:PUBLIC|CONNECTIONS>] [--media-urls <media-urls:value1,value2>] [--raw <json>]",
    "flags": "--text <text> [--visibility <visibility:PUBLIC|CONNECTIONS>] [--media-urls <media-urls:value1,value2>] [--raw <json>]"
  },
  {
    "name": "linkedin-get-person-urn",
    "description": "",
    "usage": "linkedin-get-person-urn [--raw <json>]",
    "flags": "[--raw <json>]"
  },
  {
    "name": "linkedin-diagnostic-user-info",
    "description": "",
    "usage": "linkedin-diagnostic-user-info [--raw <json>]",
    "flags": "[--raw <json>]"
  }
] as const;
const embeddedMetadata = {
  "schemaVersion": 1,
  "generatedAt": "2026-06-24T16:24:27.353Z",
  "generator": {
    "name": "mcporter",
    "version": "0.9.0"
  },
  "server": {
    "name": "linkedin",
    "source": {
      "kind": "local",
      "path": "/home/maeste/knowledge-bases/agent-me-kb/config/mcporter.json"
    },
    "definition": {
      "name": "linkedin",
      "description": "LinkedInMCP",
      "command": {
        "kind": "stdio",
        "command": "/home/maeste/.hermes/node/bin/linkedin-mcp",
        "args": [],
        "cwd": "/home/maeste/knowledge-bases/agent-me-kb/config"
      },
      "auth": "oauth"
    }
  },
  "artifact": {
    "path": "",
    "kind": "template"
  },
  "invocation": {
    "serverRef": "linkedin",
    "configPath": "/home/maeste/knowledge-bases/agent-me-kb/config/mcporter.json",
    "runtime": "node",
    "bundler": "rolldown",
    "timeoutMs": 30000,
    "minify": false
  }
} as const;
const artifactKind = determineArtifactKind();
const program = new Command();
program.name(embeddedName);
program.description(embeddedDescription);
program.option('-t, --timeout <ms>', 'Call timeout in milliseconds', (value) => parseInt(value, 10), 30000);
program.option('-o, --output <format>', 'Output format: text|markdown|json|raw', 'text');
const commandSignatures: Record<string, string> = {
  "linkedin-login": "function linkedin_login();",
  "linkedin-callback": "function linkedin_callback(code: string, state: string);",
  "linkedin-check-auth": "function linkedin_check_auth();",
  "linkedin-logout": "function linkedin_logout();",
  "linkedin-create-post": "function linkedin_create_post(text: string, visibility?: \"PUBLIC\" | \"CONNECTIONS\", mediaUrls?: string[]);",
  "linkedin-get-person-urn": "function linkedin_get_person_urn();",
  "linkedin-diagnostic-user-info": "function linkedin_diagnostic_user_info();"
};
program.configureHelp({
	commandTerm(cmd) {
		const term = cmd.name();
		return commandSignatures[term] ?? cmd.name();
	},
});
program.showSuggestionAfterError(true);

program
	.command("linkedin-login")
	.summary("linkedin-login [--raw <json>]")
	.description("Invoke the linkedin_login tool.")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	
	.alias("linkedin_login")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.linkedinLogin as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call linkedin.linkedin_login()");

program
	.command("linkedin-callback")
	.summary("linkedin-callback --code <code> --state <state> [--raw <json>]")
	.description("Invoke the linkedin_callback tool.")
	.usage("--code <code> --state <state> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--code <code>", "Code d'autorisation reçu de LinkedIn")
	.requiredOption("--state <state>", "État de la requête pour vérification")
	
	.alias("linkedin_callback")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.code !== undefined) args.code = cmdOpts.code;
		if (cmdOpts.state !== undefined) args.state = cmdOpts.state;
			const call = (proxy.linkedinCallback as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call linkedin.linkedin_callback(code: \"value\", state: \"value\")");

program
	.command("linkedin-check-auth")
	.summary("linkedin-check-auth [--raw <json>]")
	.description("Invoke the linkedin_check_auth tool.")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	
	.alias("linkedin_check_auth")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.linkedinCheckAuth as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call linkedin.linkedin_check_auth()");

program
	.command("linkedin-logout")
	.summary("linkedin-logout [--raw <json>]")
	.description("Invoke the linkedin_logout tool.")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	
	.alias("linkedin_logout")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.linkedinLogout as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call linkedin.linkedin_logout()");

program
	.command("linkedin-create-post")
	.summary("linkedin-create-post --text <text> [--visibility <visibility:PUBLIC|CONNECTIONS>] [--media-urls <media-urls:value1,value2>] [--raw <json>]")
	.description("Invoke the linkedin_create_post tool.")
	.usage("--text <text> [--visibility <visibility:PUBLIC|CONNECTIONS>] [--media-urls <media-urls:value1,value2>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--text <text>", "Contenu textuel de la publication")
	.option("--visibility <visibility:PUBLIC|CONNECTIONS>", "Visibilité de la publication (choices: PUBLIC, CONNECTIONS; default: PUBLIC; example: PUBLIC)")
	.option("--media-urls <media-urls:value1,value2>", "URLs des médias à joindre à la publication (example: value1,value2)", (value) => value.split(',').map((v) => v.trim()))
	
	.alias("linkedin_create_post")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.text !== undefined) args.text = cmdOpts.text;
		if (cmdOpts.visibility !== undefined) args.visibility = cmdOpts.visibility;
		if (cmdOpts.mediaUrls !== undefined) args.mediaUrls = cmdOpts.mediaUrls;
			const call = (proxy.linkedinCreatePost as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call linkedin.linkedin_create_post(text: \"value\", visibility: \"PU, ...)");

program
	.command("linkedin-get-person-urn")
	.summary("linkedin-get-person-urn [--raw <json>]")
	.description("Invoke the linkedin_get_person_urn tool.")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	
	.alias("linkedin_get_person_urn")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.linkedinGetPersonUrn as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call linkedin.linkedin_get_person_urn()");

program
	.command("linkedin-diagnostic-user-info")
	.summary("linkedin-diagnostic-user-info [--raw <json>]")
	.description("Invoke the linkedin_diagnostic_user_info tool.")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	
	.alias("linkedin_diagnostic_user_info")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.linkedinDiagnosticUserInfo as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call linkedin.linkedin_diagnostic_user_info()");

program
	.command('__mcporter_inspect', { hidden: true })
	.description('Internal metadata printer for mcporter inspect-cli.')
	.action(() => {
		const payload = buildMetadataPayload();
		console.log(JSON.stringify(payload, null, 2));
	});

configureToolCommandHelps();

const FORCE_COLOR = process.env.FORCE_COLOR?.toLowerCase();
const forceDisableColor = FORCE_COLOR === '0' || FORCE_COLOR === 'false';
const forceEnableColor = FORCE_COLOR === '1' || FORCE_COLOR === 'true' || FORCE_COLOR === '2' || FORCE_COLOR === '3';
const hasNoColor = process.env.NO_COLOR !== undefined;
const stdoutStream = process.stdout as NodeJS.WriteStream | undefined;
const supportsAnsiColor = !hasNoColor && (forceEnableColor || (!forceDisableColor && Boolean(stdoutStream?.isTTY)));

const tint = {
	bold(text: string): string {
		return supportsAnsiColor ? '[1m' + text + '[0m' : text;
	},
	dim(text: string): string {
		return supportsAnsiColor ? '[90m' + text + '[0m' : text;
	},
	extraDim(text: string): string {
		return supportsAnsiColor ? '[38;5;244m' + text + '[0m' : text;
	},
};

function configureGeneratedCommandHelp(command: Command): void {
	command.configureHelp({
		commandUsage(target) {
			const usage = (target.name() + ' ' + target.usage()).trim() || target.name();
			return supportsAnsiColor ? tint.bold(usage) : usage;
		},
		optionTerm(option) {
			const term = option.flags ?? '';
			return supportsAnsiColor ? tint.bold(term) : term;
		},
		optionDescription(option) {
			const description = option.description ?? '';
			return supportsAnsiColor ? tint.extraDim(description) : description;
		},
	});
}

function configureToolCommandHelps(): void {
	program.commands.forEach((cmd) => {
		if (cmd.name() === '__mcporter_inspect') {
			return;
		}
		configureGeneratedCommandHelp(cmd);
	});
}

function renderStandaloneHelp(): string {
	const colorfulTitle = tint.bold(embeddedName) + ' ' + tint.dim('— ' + embeddedDescription);
	const plainTitle = embeddedName + ' — ' + embeddedDescription;
	const title = supportsAnsiColor ? colorfulTitle : plainTitle;
	const lines = [title, '', 'Usage: ' + embeddedName + ' <command> [options]', ''];
	if (generatorTools) {
		lines.push(formatEmbeddedTools());
	}
	lines.push('', formatGlobalFlags(), '', formatQuickStart());
	if (generatorInfo) {
		lines.push('', tint.extraDim(generatorInfo));
	}
	return lines.join('\n');
}

program.helpInformation = () => renderStandaloneHelp();

function formatEmbeddedTools(): string {
	const header = supportsAnsiColor ? tint.bold('Embedded tools') : 'Embedded tools';
	if (!generatorTools.length) {
		return header;
	}
	const lines = [header];
	generatorTools.forEach((entry) => {
		const renderedDesc = entry.description
			? supportsAnsiColor
				? tint.extraDim(entry.description)
				: entry.description
			: undefined;
		const base = renderedDesc ? entry.name + ' - ' + renderedDesc : entry.name;
		lines.push('  ' + base);
		if (entry.flags) {
			const renderedFlags = supportsAnsiColor ? tint.extraDim(entry.flags) : entry.flags;
			lines.push('    ' + renderedFlags);
		}
		lines.push('');
	});
	if (lines[lines.length - 1] === '') {
		lines.pop();
	}
	return lines.join('\n');
}

function formatGlobalFlags(): string {
	const header = supportsAnsiColor ? tint.bold('Global flags') : 'Global flags';
	const entries = [
		['-t, --timeout <ms>', 'Call timeout in milliseconds'],
		['-o, --output <format>', 'text | markdown | json | raw (default text)'],
	];
	const formatted = entries.map(([flag, summary]) => '  ' + flag.padEnd(28) + summary);
	return [header, ...formatted].join('\n');
}

function formatQuickStart(): string {
  const header = supportsAnsiColor ? tint.bold('Quick start') : 'Quick start';
  const examples = quickStartExamples();
  if (!examples.length) {
    return header;
  }
  const formatted = examples.map(([cmd, note]) => '  ' + cmd + '\n    ' + tint.dim('# ' + note));
  return [header, ...formatted].join('\n');
}

function quickStartExamples(): Array<[string, string]> {
  const examples: Array<[string, string]> = [];
  const commandMap = new Map<string, string>();
  program.commands.forEach((cmd) => {
    const name = cmd.name();
    if (name !== '__mcporter_inspect') {
      commandMap.set(name, name);
    }
  });
  const embedded = Array.isArray(generatorTools) ? generatorTools : [];
  for (const entry of embedded.slice(0, 3)) {
    const commandName = commandMap.get(entry.name) ?? entry.name;
    const flags = entry.flags ? ' ' + entry.flags.replace(/<[^>]+>/g, '<value>') : '';
    examples.push([embeddedName + ' ' + commandName + flags, 'invoke ' + commandName]);
  }
  if (!examples.length) {
    examples.push([embeddedName + ' <tool> --key value', 'invoke a tool with flags']);
  }
  return examples;
}


function printResult(result: unknown, format: string) {
	const wrapped = createCallResult(result);
	switch (format) {
		case 'json': {
			const json = wrapped.json();
			if (json) {
				console.log(JSON.stringify(json, null, 2));
				return;
			}
			break;
		}
		case 'markdown': {
			const markdown = wrapped.markdown();
			if (markdown) {
				console.log(markdown);
				return;
			}
			break;
		}
		case 'raw': {
			console.log(JSON.stringify(wrapped.raw, null, 2));
			return;
		}
	}
	const text = wrapped.text();
	if (text) {
		console.log(text);
	} else {
		console.log(JSON.stringify(wrapped.raw, null, 2));
	}
}

function normalizeEmbeddedServer(server: typeof embeddedServer) {
	const base = { ...server } as Record<string, unknown>;
	if ((server.command as any).kind === 'http') {
		const urlRaw = (server.command as any).url;
		const urlValue = typeof urlRaw === 'string' ? urlRaw : String(urlRaw);
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				url: new URL(urlValue),
			},
		};
	}
	if ((server.command as any).kind === 'stdio') {
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				args: [ ...((server.command as any).args ?? []) ],
			},
		};
	}
	return base;
}

function determineArtifactKind(): 'template' | 'bundle' | 'binary' {
	const scriptPath = typeof process !== 'undefined' && Array.isArray(process.argv) ? process.argv[1] ?? '' : '';
	if (scriptPath.endsWith('.ts')) {
		return 'template';
	}
	if (scriptPath.endsWith('.js')) {
		return 'bundle';
	}
	return 'binary';
}

function resolveArtifactPath(): string {
	if (typeof process !== 'undefined' && Array.isArray(process.argv) && process.argv.length > 1) {
		const script = process.argv[1];
		if (script) {
			return script;
		}
	}
	return embeddedMetadata.artifact.path;
}

function buildMetadataPayload() {
	const invocation = { ...embeddedMetadata.invocation };
	const path = resolveArtifactPath();
	if (artifactKind === 'template' && path) {
		invocation.outputPath = invocation.outputPath ?? path;
	} else if (artifactKind === 'bundle' && path) {
		invocation.bundle = invocation.bundle ?? path;
	} else if (artifactKind === 'binary' && path) {
		invocation.compile = invocation.compile ?? path;
	}
	return {
		...embeddedMetadata,
		artifact: {
			path,
			kind: artifactKind,
		},
		invocation,
	};
}

async function ensureRuntime(): Promise<Awaited<ReturnType<typeof createRuntime>>> {
	return await createRuntime({
		servers: [normalizeEmbeddedServer(embeddedServer)],
	});
}

async function invokeWithTimeout<T>(call: Promise<T>, timeout: number): Promise<T> {
	if (!Number.isFinite(timeout) || timeout <= 0) {
		return await call;
	}
	let timer: ReturnType<typeof setTimeout> | undefined;
	try {
		return await Promise.race([
			call,
			new Promise<never>((_, reject) => {
				timer = setTimeout(() => {
					reject(new Error('Call timed out after ' + timeout + 'ms.'));
				}, timeout);
			}),
		]);
	} finally {
		if (timer) {
			clearTimeout(timer);
		}
	}
}

async function runCli(): Promise<void> {
	const args = process.argv.slice(2);
	if (args.length === 0) {
		program.outputHelp();
		return;
	}
	await program.parseAsync(process.argv);
}

if (process.env.MCPORTER_DISABLE_AUTORUN !== '1') {
	runCli().catch((error) => {
		const message = error instanceof Error ? error.message : String(error);
		console.error(message);
		process.exit(1);
	});
}
